export const ROLE_CHANGE_CONFIRMATION = "ROLE CHANGE";
export const TRUST_CHANGE_CONFIRMATION = "TRUST CHANGE";
export const BULK_SESSION_CONFIRMATION = "REVOKE SESSIONS";
export const AUDIT_EXPORT_CONFIRMATION = "EXPORT AUDIT";
export const SITE_SETTINGS_CONFIRMATION = "NEXTBUF";
