import "server-only";

import type {
  CommunityHomeView,
  CommunityNodeView,
  CommunityTopicView,
} from "@/modules/community/contracts/home-view";

function avatar(seed: string, backgroundColor: string): string {
  return `https://api.dicebear.com/9.x/thumbs/svg?seed=${seed}&backgroundColor=${backgroundColor}`;
}

const nodes: CommunityNodeView[] = [
  { id: "all", name: "全部话题", color: "#18181b", icon: "grid", topicCount: 9 },
  { id: "ai", name: "人工智能", color: "#7c3aed", icon: "bot", topicCount: 2 },
  { id: "site", name: "建站开发", color: "#2563eb", icon: "code", topicCount: 2 },
  { id: "host", name: "主机云服务", color: "#0f766e", icon: "server", topicCount: 1 },
  { id: "domain", name: "域名 DNS", color: "#c2410c", icon: "globe", topicCount: 1 },
  { id: "ops", name: "运维网络", color: "#0369a1", icon: "network", topicCount: 2 },
  { id: "showcase", name: "项目展示", color: "#be185d", icon: "sparkles", topicCount: 1 },
];

const topics: CommunityTopicView[] = [
  {
    id: 1,
    title: "独立开发者做 AI 产品，信息流怎样不被算法带偏？",
    nodeId: "ai",
    nodeName: "人工智能",
    nodeColor: "#7c3aed",
    authorName: "Mika",
    authorAvatarUrl: avatar("mika", "fde68a"),
    authorInitials: "MI",
    createdLabel: "3 小时前",
    lastReplyLabel: "18 分钟前",
    lastReplyBy: "Kino",
    views: 1260,
    replies: 28,
    statuses: ["pinned", "hot", "essence"],
  },
  {
    id: 2,
    title: "求推荐：适合中文技术社区的轻量论坛技术栈",
    nodeId: "site",
    nodeName: "建站开发",
    nodeColor: "#2563eb",
    authorName: "Haze",
    authorAvatarUrl: avatar("haze", "bbf7d0"),
    authorInitials: "HA",
    createdLabel: "2 小时前",
    lastReplyLabel: "40 分钟前",
    lastReplyBy: "Oak",
    views: 842,
    replies: 19,
    statuses: ["hot"],
  },
  {
    id: 3,
    title: "2026 性价比 VPS 横评：线路、稳定性、售后怎么看",
    nodeId: "host",
    nodeName: "主机云服务",
    nodeColor: "#0f766e",
    authorName: "Oak",
    authorAvatarUrl: avatar("oak", "c7d2fe"),
    authorInitials: "OA",
    createdLabel: "昨天",
    lastReplyLabel: "1 小时前",
    lastReplyBy: "Rex",
    views: 2210,
    replies: 34,
    statuses: ["hot", "essence"],
  },
  {
    id: 4,
    title: "域名转入后 DNS 生效慢，怎么系统性排查？",
    nodeId: "domain",
    nodeName: "域名 DNS",
    nodeColor: "#c2410c",
    authorName: "June",
    authorAvatarUrl: avatar("june", "fbcfe8"),
    authorInitials: "JU",
    createdLabel: "昨天",
    lastReplyLabel: "2 小时前",
    lastReplyBy: "Sora",
    views: 560,
    replies: 12,
    statuses: [],
  },
  {
    id: 5,
    title: "从零部署一个可公开访问的 AI Web App 清单",
    nodeId: "ops",
    nodeName: "运维网络",
    nodeColor: "#0369a1",
    authorName: "Kino",
    authorAvatarUrl: avatar("kino", "bfdbfe"),
    authorInitials: "KI",
    createdLabel: "2 天前",
    lastReplyLabel: "3 小时前",
    lastReplyBy: "Haze",
    views: 980,
    replies: 21,
    statuses: ["hot", "essence"],
  },
  {
    id: 6,
    title: "展示：我给社区做的信任等级进度卡片",
    nodeId: "showcase",
    nodeName: "项目展示",
    nodeColor: "#be185d",
    authorName: "Nori",
    authorAvatarUrl: avatar("nori", "fed7aa"),
    authorInitials: "NO",
    createdLabel: "2 天前",
    lastReplyLabel: "昨天",
    lastReplyBy: "柚柚",
    views: 720,
    replies: 15,
    statuses: ["essence"],
  },
  {
    id: 7,
    title: "小站反垃圾：新用户外链和发帖频率怎么设？",
    nodeId: "site",
    nodeName: "建站开发",
    nodeColor: "#2563eb",
    authorName: "Rex",
    authorAvatarUrl: avatar("rex", "ddd6fe"),
    authorInitials: "RE",
    createdLabel: "3 天前",
    lastReplyLabel: "昨天",
    lastReplyBy: "Oak",
    views: 640,
    replies: 18,
    statuses: [],
  },
  {
    id: 8,
    title: "Cloudflare + 源站回源优化，有哪些常见坑？",
    nodeId: "ops",
    nodeName: "运维网络",
    nodeColor: "#0369a1",
    authorName: "Sora",
    authorAvatarUrl: avatar("sora", "e9d5ff"),
    authorInitials: "SO",
    createdLabel: "4 天前",
    lastReplyLabel: "2 天前",
    lastReplyBy: "Oak",
    views: 690,
    replies: 14,
    statuses: [],
  },
  {
    id: 9,
    title: "用 AI 辅助写部署文档，怎样避免看起来对、实际跑不通？",
    nodeId: "ai",
    nodeName: "人工智能",
    nodeColor: "#7c3aed",
    authorName: "阿南",
    authorAvatarUrl: avatar("linan", "d1fae5"),
    authorInitials: "南",
    createdLabel: "5 天前",
    lastReplyLabel: "3 天前",
    lastReplyBy: "Mika",
    views: 810,
    replies: 16,
    statuses: ["essence"],
  },
];

export function getDemoCommunityHome(): CommunityHomeView {
  return {
    currentUser: {
      name: "阿南",
      username: "linan",
      uid: 10086,
      avatarUrl: avatar("linan", "d1fae5"),
      initials: "南",
      trustLevel: 3,
      trustName: "老手",
      trustProgress: 78,
      nextTrustLevel: 4,
      joinedDays: 126,
      topicCount: 18,
      replyCount: 132,
    },
    nodes,
    topics,
    notifications: [
      {
        id: 1,
        actorName: "Kino",
        actorAvatarUrl: avatar("kino", "bfdbfe"),
        actorInitials: "KI",
        title: "回复了你的话题",
        description: "轻量社区首版，先把节点、列表和信任等级做扎实。",
        timeLabel: "12 分钟前",
        unread: true,
      },
      {
        id: 2,
        actorName: "Oak",
        actorAvatarUrl: avatar("oak", "c7d2fe"),
        actorInitials: "OA",
        title: "提到了你",
        description: "主机线路这块建议补上晚高峰实测。",
        timeLabel: "46 分钟前",
        unread: true,
      },
      {
        id: 3,
        actorName: "Mika",
        actorAvatarUrl: avatar("mika", "fde68a"),
        actorInitials: "MI",
        title: "赞了你的回复",
        description: "关于信任等级和管理角色分开的讨论。",
        timeLabel: "2 小时前",
        unread: true,
      },
    ],
    overview: [
      { label: "成员", value: "2,418" },
      { label: "话题", value: "6,892" },
      { label: "今日回复", value: "184" },
      { label: "当前在线", value: "96" },
    ],
    onlineMembers: [
      { name: "Mika", avatarUrl: avatar("mika", "fde68a"), initials: "MI" },
      { name: "Kino", avatarUrl: avatar("kino", "bfdbfe"), initials: "KI" },
      { name: "Oak", avatarUrl: avatar("oak", "c7d2fe"), initials: "OA" },
      { name: "Sora", avatarUrl: avatar("sora", "e9d5ff"), initials: "SO" },
      { name: "Nori", avatarUrl: avatar("nori", "fed7aa"), initials: "NO" },
    ],
  };
}
