nodeLinker: hoisted

allowBuilds:
  "@prisma/engines": true
  msgpackr-extract: false
  prisma: true
  sharp: true
overrides:
  "@hono/node-server": 2.0.11
  fast-uri: 3.1.5
minimumReleaseAgeExclude:
  - "@prisma/adapter-pg@7.9.1"
  - "@prisma/client-runtime-utils@7.9.1"
  - "@prisma/client@7.9.1"
  - "@prisma/config@7.9.1"
  - "@prisma/debug@7.9.1"
  - "@prisma/driver-adapter-utils@7.9.1"
  - "@prisma/engines@7.9.1"
  - "@prisma/fetch-engine@7.9.1"
  - "@prisma/get-platform@7.9.1"
  - prisma@7.9.1
